// src/components/ArticleList/ArticleList.vue
<template>
      <!-- <div
        v-for="articleData in nostrArticles"
        className="ArticleList"
      > -->
      <!-- <Article key={articleData.id} item={articleData} /> -->
      <Article />
    <!-- </div> -->
</template>

<script>
/* eslint-disable vue/require-v-for-key */
import './ArticleList.scss'
import Article from '../Article/Article.vue'
// import { nostrEventState } from 'src/application/states/relay.state';

export default {
  name: 'ArticleList',
  components: {
    Article
  }
}
</script>

// src/components/ArticleList/ArticleList.component.tsx
import './ArticleList.style.scss';

import React from 'react';
import { useRecoilValue } from 'recoil';

import { nostrEventState } from 'src/application/states/relay.state';
import Article from '../Article/Article.component';

const ArticleList: React.FC = () => {
  const nostrArticles = useRecoilValue(nostrEventState);

  return (
    <div className="ArticleList">
      {nostrArticles.map(articleData => (
        <Article key={articleData.id} item={articleData} />
      ))}
    </div>
  );
};

export default ArticleList;
