// src/components/Footer/Footer.vue
<template>
  <div class="footer-div">
    <q-footer class="footer-container">
      <q-toolbar>
        <q-toolbar-title
          >© 2022 Cynsar Foundation
          <br />
          <div class="footer-2">
            Visit
            <a href="https://github.com/muellners/second.exchange"
              >Second Exchange GitHub repository</a
            >
            to contribute to the source code
          </div>
          <div>
          <a href="https://www.netlify.com/">This site is powered by Netlify</a>
          </div>
        </q-toolbar-title>
      </q-toolbar>
    </q-footer>
  </div>
</template>
<script>
import './Footer.scss'

export default {
  name: 'Footer'
}
</script>

// src/components/Layouts/Footer.tsx
import { Box, Text, Flex, useColorModeValue } from "@chakra-ui/react";
import React from "react";
import { AiOutlineGithub } from "react-icons/ai";

type FooterProps = {};

const Footer: React.FC<FooterProps> = () => {
  return (
    <Box
      borderTop="0.5px solid"
      borderColor={useColorModeValue("#cbcbcb", "brand.100")}
      display="flex"
      flexDirection="column"
      alignItems="center"
      justifyContent="center"
      rowGap="5px"
      position="absolute"
      bottom={0}
      width="100%"
      p="5px"
    >
      <Text>
        Made at{" "}
        <a
          href="https://github.com/muellners"
          color={useColorModeValue("brand.100", "brand.200")}
        >
          Muellners Foundation
        </a>
      </Text>
      <Flex alignItems="center">
        <Text pr="5px" fontSize="20px">
          Contribute to Second Exchange on
        </Text>
        <a href="https://github.com/muellners/second.exchange">
          <AiOutlineGithub fontSize="20px" />
        </a>
      </Flex>
      <a href="https://www.netlify.com/">
        <Text
          cursor="pointer"
          textDecoration="underline"
          color={useColorModeValue("brand.100", "brand.200")}
        >
          This site is powered by Netlify
        </Text>
      </a>
    </Box>
  );
};
export default Footer;
